### ISSUE TITLE
Projektek - hibajavítások

### ISSUE THREAD

**Issue by csabafejes** [d3rang3/mediaio#169]
- [x] A projekt leírása ne a képen látható módon jelenjen meg gépen, hanem hasonlóan a mobilos nézethez, a legfelső task felett.

![Screenshot (3)](https://github.com/gutasiadam/mediaio/assets/132352207/b7b26d69-b644-45a4-b5e9-5a9d31094bd2)

További hibajavítások / fejlesztések:
- [x] Automata frissítés ritkítása, az üzenet méretének csökkentése (esetleg csak akkor frissíteni, ha történt változás)
- [x] Válaszok megtekintése adminok számára (nem kell, hogy a taskhoz hozzárendelt legyen)
- [x] Válaszokban pirossal jelölés, ha valaki késve adja le 
<img width="538" alt="image" src="https://github.com/gutasiadam/mediaio/assets/75137914/ef8bfc7f-c66a-46b4-8768-b2208eb0941d">

- [x] Válaszok megtekintése adminoknak és a task letrehozójának, az előtt, hogy kitöltötte volna a feladatot
- [x] Új project hozzáadása legyen placeholder a végén adminoknak
- [x] Taskok rendezése alapból a deadline szerint

**Comment by krkskmate** [comment]
Ha igy csináljuk nem marad hely a task kartyaknak! Szerintem érdemes lenne egy "nagy nézet" gépen is ahol akar több oszlopban az adott projekt taskjai jelennek meg. Külön részen részletes információk a projektről a leírásával együtt.

**Comment by gutasiadam** [comment]
Ha ráhuzod az egered egy feladatnál a hatralévő időre akkor írja a pontos dátumot ( hasonlóan mint azt, hogy ki készítette az adott feladatot ha ráhúzod az egered az infó ikonra )
