### ISSUE TITLE
IO Hibajavítások/Fejlesztések

### ISSUE THREAD

**Issue by foldesa** [d3rang3/mediaio#170]
Engedélyek módosítása:
- [x] A böngészős felugró ablak kiszedése<img width="1440" alt="image" src="https://github.com/gutasiadam/mediaio/assets/75137914/6ef215fe-4ff3-4f56-9874-d5fe8d417a66">
- [x] Mentés után frissíteni kellene az oldalt

 Leltár:
- [x] A stúdiós dolgok legyen primary színű
- [x] A UID szerinti rendezés igazából ID szerint legyen rendezve 
- [x] A kintlévő dolgok legyenek warning színűek (Bocsi az előbb danger-t írtam, de warningra gondoltam)

Profil:
- [x] E gomb funkciójának ellenőrzése, funkció hiányában az eltávolítása.
<img width="461" alt="image" src="https://github.com/gutasiadam/mediaio/assets/75137914/fcd9e90a-06f6-4b30-8af7-686a227843d2">

- [x]  A nálam lévő dolgok eltávolítása valamint a kapcsolódásainak is, ha van.
- [x]  A tárgytörténet áthelyezése a profil oldalra, csak adminok (vagy magasabb) számára legyen elérhető

Jóváhagyás:
- [x] Eszköz neve mellé a UID feltüntetée
- [x] A JSON oszlop eltüntetése
- [x] A jóváhagyás elvetésekor nem jól írja be az adatbázisba, ezért NULL-nál lesz az adott eszköz
<img width="1310" alt="image" src="https://github.com/gutasiadam/mediaio/assets/75137914/690eee60-9df8-456b-a839-12753c1a28b4">

- [x] AZ adott kivételből csak bizonyos tételt is lehessen visszamondani ne csak az egészet

Naptár:
- [x] A naptár és a hozzá kapcsolódó fájlok átvizsgálása, a használaton kívüli részek kiírása
- [x] Kinézet javítása 

Kivétel:
- [x] Szűrök létrehozása (kb mint a leltárban), hogy ne csak az elérhető nem elérhetőt lehessen állítani, hanem az összes többit is
- [x] A presetekben ne csak item-et lehessen beadni, hanem category-t is 
- [x] Egy preset kiválasztásakor írja, hogy abból mik nem elérhetők
- [x] A preset bugos, mert ha olyan UID van benne, ami nem létezik, akkor az azután következő, létezőket sem jelöli ki
- [x] Category alapján szűrés

**Comment by krkskmate** [comment]
Presetekben maradnak előre beállított megoldások.
Szűrési lehetőségek között lesz kategória alapján!

**Comment by foldesa** [comment]
erre gondolok a preset változás alatt, hogy itt ha az van hogy {"Category": ["fresnel"]} akkor az összes olyat, aminek az a Category-ja azt vegye ki 
<img width="476" alt="image" src="https://github.com/gutasiadam/mediaio/assets/75137914/d8cb7d78-a43f-49d1-af8b-eeea99805332">
